var group__ass =
[
    [ "ass::BackgroundCropping", "structass_1_1BackgroundCropping.html", null ],
    [ "ass::BackgroundGradient", "structass_1_1BackgroundGradient.html", null ],
    [ "ass::BackgroundImage", "structass_1_1BackgroundImage.html", null ],
    [ "ass::BackgroundSolid", "structass_1_1BackgroundSolid.html", null ],
    [ "ass::Border", "structass_1_1Border.html", null ],
    [ "ass::BorderBottom", "structass_1_1BorderBottom.html", null ],
    [ "ass::BorderLeft", "structass_1_1BorderLeft.html", null ],
    [ "ass::BorderRadius", "structass_1_1BorderRadius.html", null ],
    [ "ass::BoxShadow", "structass_1_1BoxShadow.html", null ],
    [ "ass::Expanding", "structass_1_1Expanding.html", null ],
    [ "ass::FixedSize", "structass_1_1FixedSize.html", null ],
    [ "ass::Font", "structass_1_1Font.html", null ],
    [ "ass::FontFamily", "structass_1_1FontFamily.html", null ],
    [ "ass::FontSize", "structass_1_1FontSize.html", null ],
    [ "ass::LayoutSpacing", "structass_1_1LayoutSpacing.html", null ],
    [ "ass::LineHeight", "structass_1_1LineHeight.html", null ],
    [ "ass::Margin", "structass_1_1Margin.html", null ],
    [ "ass::MaxSize", "structass_1_1MaxSize.html", null ],
    [ "ass::MinSize", "structass_1_1MinSize.html", null ],
    [ "ass::Opacity", "structass_1_1Opacity.html", null ],
    [ "ass::Padding", "structass_1_1Padding.html", null ],
    [ "ass::TextBorder", "structass_1_1TextBorder.html", null ],
    [ "ass::TextColor", "structass_1_1TextColor.html", null ],
    [ "ass::TextShadow", "structass_1_1TextShadow.html", null ],
    [ "ass::TransformOffset", "structass_1_1TransformOffset.html", null ],
    [ "ass::TransformScale", "structass_1_1TransformScale.html", null ],
    [ "ACursor", "group__ass.html#ga5246afc4bdd66935850032716ae2a5be", [
      [ "ACursor::DEFAULT", "group__ass.html#gga5246afc4bdd66935850032716ae2a5bea5b39c8b553c821e7cddc6da64b5bd2ee", null ],
      [ "ACursor::POINTER", "group__ass.html#gga5246afc4bdd66935850032716ae2a5beaa5f41c79d3f86121f0f658eba49128d5", null ],
      [ "ACursor::TEXT", "group__ass.html#gga5246afc4bdd66935850032716ae2a5bea61a96ffcb251bb9bf0abf8fec19d0ea8", null ]
    ] ],
    [ "VerticalAlign", "group__ass.html#ga327847b397ac5aa9eefa2157dbe0961d", null ]
];