var namespaces =
[
    [ "ADesktop", "namespaceADesktop.html", "namespaceADesktop" ],
    [ "AHash", "namespaceAHash.html", null ],
    [ "APlatform", "namespaceAPlatform.html", null ],
    [ "aui", null, [
      [ "parameter_pack", "namespaceaui_1_1parameter__pack.html", null ],
      [ "assert_not_used_when_null", "classaui_1_1assert__not__used__when__null.html", null ],
      [ "atomic_lazy", "structaui_1_1atomic__lazy.html", null ],
      [ "BinarySearchNearestToZero", "structaui_1_1BinarySearchNearestToZero.html", null ],
      [ "fast_pimpl", "structaui_1_1fast__pimpl.html", null ],
      [ "function_info", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(&)(Args...) noexcept >", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(&)(Args...)>", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(*)(Args...) noexcept >", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(*)(Args...)>", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(Args...) noexcept >", "structaui_1_1function__info.html", null ],
      [ "function_info< Return(Args...)>", "structaui_1_1function__info.html", null ],
      [ "HVLayout", "structaui_1_1HVLayout.html", null ],
      [ "identity", "structaui_1_1identity.html", null ],
      [ "lambda_overloaded", "structaui_1_1lambda__overloaded.html", null ],
      [ "lazy", "structaui_1_1lazy.html", null ],
      [ "lazy< void >", "structaui_1_1lazy.html", null ],
      [ "member", "structaui_1_1member.html", null ],
      [ "member< Type(Clazz::*)(Args...) const >", "structaui_1_1member.html", "structaui_1_1member" ],
      [ "member< Type(Clazz::*)(Args...) const noexcept >", "structaui_1_1member.html", "structaui_1_1member" ],
      [ "member< Type(Clazz::*)(Args...) noexcept >", "structaui_1_1member.html", "structaui_1_1member" ],
      [ "member< Type(Clazz::*)(Args...)>", "structaui_1_1member.html", "structaui_1_1member" ],
      [ "member< Type(Clazz::*)>", "structaui_1_1member.html", null ],
      [ "no_escape", "structaui_1_1no__escape.html", null ],
      [ "non_null", "structaui_1_1non__null.html", null ],
      [ "non_null_lateinit", "structaui_1_1non__null__lateinit.html", null ],
      [ "noncopyable", "structaui_1_1noncopyable.html", null ],
      [ "ptr", "structaui_1_1ptr.html", null ],
      [ "range", "structaui_1_1range.html", null ],
      [ "ranged_number", "structaui_1_1ranged__number.html", null ],
      [ "raw_serializable", "structaui_1_1raw__serializable.html", null ],
      [ "reverse_iterator_wrap", "structaui_1_1reverse__iterator__wrap.html", null ],
      [ "sequence_traits", "structaui_1_1sequence__traits.html", "structaui_1_1sequence__traits" ],
      [ "serialize_raw", "structaui_1_1serialize__raw.html", null ],
      [ "serialize_sized", "structaui_1_1serialize__sized.html", null ],
      [ "ternary", "structaui_1_1ternary.html", null ],
      [ "ternary< std::false_type, OnTrue, OnFalse >", "structaui_1_1ternary.html", null ],
      [ "ternary< std::true_type, OnTrue, OnFalse >", "structaui_1_1ternary.html", null ],
      [ "tuple_visitor", "structaui_1_1tuple__visitor.html", null ],
      [ "tuple_visitor< std::tuple< Args... > >", "structaui_1_1tuple__visitor.html", null ],
      [ "zip", "structaui_1_1zip.html", "structaui_1_1zip" ],
      [ "not_overloaded_lambda", "conceptaui_1_1not__overloaded__lambda.html", null ],
      [ "function_pointer", "conceptaui_1_1function__pointer.html", null ],
      [ "derived_from", "conceptaui_1_1derived__from.html", null ],
      [ "invocable", "conceptaui_1_1invocable.html", null ],
      [ "convertible_to", "conceptaui_1_1convertible__to.html", null ],
      [ "destructible", "conceptaui_1_1destructible.html", null ],
      [ "constructible_from", "conceptaui_1_1constructible__from.html", null ],
      [ "move_constructible", "conceptaui_1_1move__constructible.html", null ],
      [ "copy_constructible", "conceptaui_1_1copy__constructible.html", null ],
      [ "same_as", "conceptaui_1_1same__as.html", null ],
      [ "common_reference_with", "conceptaui_1_1common__reference__with.html", null ],
      [ "assignable_from", "conceptaui_1_1assignable__from.html", null ],
      [ "swappable", "conceptaui_1_1swappable.html", null ],
      [ "movable", "conceptaui_1_1movable.html", null ],
      [ "copyable", "conceptaui_1_1copyable.html", null ],
      [ "default_initializable", "conceptaui_1_1default__initializable.html", null ],
      [ "semiregular", "conceptaui_1_1semiregular.html", null ],
      [ "regular", "conceptaui_1_1regular.html", null ],
      [ "incrementable", "conceptaui_1_1incrementable.html", null ],
      [ "predicate", "conceptaui_1_1predicate.html", null ],
      [ "mapper", "conceptaui_1_1mapper.html", null ],
      [ "factory", "conceptaui_1_1factory.html", null ],
      [ "arithmetic", "conceptaui_1_1arithmetic.html", null ],
      [ "unsigned_integral", "conceptaui_1_1unsigned__integral.html", null ],
      [ "is_tuple", "conceptaui_1_1is__tuple.html", null ],
      [ "pointer_to_member", "conceptaui_1_1pointer__to__member.html", null ],
      [ "args", "group__core.html#ga537f82748636c62d35a8ec4ed38a0fe0", null ],
      [ "importPlugin", "group__core.html#ga2305696ff6358034fab947ca8cd7812a", null ],
      [ "importPluginPath", "group__core.html#ga0088806c40549a1bc72ea08cdb864be9", null ],
      [ "indexOf", "group__core.html#ga4cfb55637d96cbb11c9c00bcb6a7998d", null ],
      [ "is_complete", "group__useful__templates.html#ga6f9bb834ae166b6625fc5c91117d8738", null ],
      [ "is_complete< T, decltype(void(sizeof(T)))>", "group__useful__templates.html#ga2f01064dbcf7bb512dcc42776ab95678", null ],
      [ "select_overload", "group__useful__templates.html#ga9457e4a0e33ad1fe42bb558b7f5a224a", null ]
    ] ],
    [ "AXml", "namespaceAXml.html", [
      [ "read", "group__xml.html#ga06fdf594d32ebd9bf8a564fd832c6f28", null ]
    ] ],
    [ "By", "namespaceBy.html", null ]
];