name: Generate xml sitemap

on:
  push:
    branches: [ main ]
    paths: [ '**.html', '**.yml' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare repo
        run: |
          git config user.name noreply
          git config user.email "noreply@github.com"
          git fetch origin main
          git checkout main

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://aui-framework.github.io/
          exclude-paths: /master

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Push update
        run: |
          git add sitemap.xml
          git commit -m "update sitemap"
          git push
